### ISSUE TITLE
Crash at startup (1.11.2) Forge 2282

### ISSUE THREAD

**Issue by Rafilondon** [BobMowzie/MowziesMobs#1]
Can't start my game with the mod installed, error log below.

`// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/15/17 2:36 PM
Description: Initializing game

java.lang.IllegalStateException: texture not set
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.build(UnpackedBakedQuad.java:173)
	at net.ilexiconn.llibrary.client.model.tabula.baked.VanillaTabulaModel.buildQuad(VanillaTabulaModel.java:223)
	at net.ilexiconn.llibrary.client.model.tabula.baked.VanillaTabulaModel.build(VanillaTabulaModel.java:140)
	at net.ilexiconn.llibrary.client.model.tabula.baked.VanillaTabulaModel.bake(VanillaTabulaModel.java:70)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:205)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:764)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:372)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.build(UnpackedBakedQuad.java:173)
	at net.ilexiconn.llibrary.client.model.tabula.baked.VanillaTabulaModel.buildQuad(VanillaTabulaModel.java:223)
	at net.ilexiconn.llibrary.client.model.tabula.baked.VanillaTabulaModel.build(VanillaTabulaModel.java:140)
	at net.ilexiconn.llibrary.client.model.tabula.baked.VanillaTabulaModel.bake(VanillaTabulaModel.java:70)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:205)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:764)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:372)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by BobMowzie** [comment]
To play on 1.11.2, use Forge 13.20.0.2233 or 13.20.0.2228, no later.

**Comment by BobMowzie** [comment]
This is an issue with LLibrary, not Mowzie's Mobs.
