### ISSUE TITLE
Strange MiencraftServer Freez with Mobs

### ISSUE THREAD

**Issue by SirAron111** [BobMowzie/MowziesMobs#116]
So I updated the mod mowzie mobs mod to 1.5.2 and now a bit of time after spawning in the world the World Freezes and you can’t do anything anymore just push around the mobs with your body but not attack them and nothing moves can’t even drop items but it isn’t a crash I have to use task manager to stop minecraft as I can’t do anything can this be fixed?

Here is a link to the log of the console:
https://pastebin.com/W4t2MzHn

**Comment by BobMowzie** [comment]
Disable lantern spawning in the config.

**Comment by nephatrine** [comment]
Yeah lanterns seem to be causing issues on my server as well. Love them so hopefully it is something easily resolved.

```
java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at net.minecraft.world.World.func_184144_a(World.java:1362)
	at com.bobmowzie.mowziesmobs.server.entity.lantern.EntityLantern$LanternMoveHelper.isNotColliding(EntityLantern.java:324)
	at com.bobmowzie.mowziesmobs.server.entity.lantern.EntityLantern$LanternMoveHelper.func_75641_c(EntityLantern.java:298)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:781)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2351)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2171)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.bobmowzie.mowziesmobs.server.entity.MowzieEntity.func_70071_h_(MowzieEntity.java:94)
	at com.bobmowzie.mowziesmobs.server.entity.lantern.EntityLantern.func_70071_h_(EntityLantern.java:71)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by LDsanya** [comment]
I noticed this oddity, Lantern sometimes causes crash, when interacting with water.

**Comment by BobMowzie** [comment]
I can't seem to replicate any of the behavior described here at all. The lanterns work just fine in both single player and multiplayer on my computer.
Does the issue persist if you disable all other mods?

**Comment by SirAron111** [comment]
https://pastebin.com/v4CBNqWX and https://pastebin.com/DasQQ7Qg I got 2 more reports of the same crash from my community the first one even mentions the lantern directly but I am running it on a modpack maybe its an mod interaction bug
Modpack "Dimension Zero"

**Comment by LDsanya** [comment]
> I can't seem to replicate any of the behavior described here at all. The lanterns work just fine in both single player and multiplayer on my computer.
> Does the issue persist if you disable all other mods?

I tested on Minecraft 1.12.2 with Forge 2807 and LLibrary 1.7.17 only, without other mods

**Comment by LDsanya** [comment]
While the client does not crash, only the server. In this case, everything in the world freezes

**Comment by BobMowzie** [comment]
SirAron The first crash you’ve listed has been fixed. Please use MM 1.5.2.
The second one is new. I’ll look into it

LDSanya The extra details help. Thanks.

**Comment by LDsanya** [comment]
One more thing, the original en_us.lang is missing the name of some potions and poisonous arrows

**Comment by Durothan** [comment]
my game freezes in single player too. I dont know why but after deleting this mod, the crashes go away
i use mowziesmobs-1.5.2

**Comment by AryaRaiin** [comment]
Current modpack I'm creating is experiencing the same lantern related crash. Running mowziesmobs-1.5.2. I haven't been able to replicate the issue in single-player.

[crash-2019-01-25_01.23.10-server.txt](https://github.com/BobMowzie/MowziesMobs/files/2794963/crash-2019-01-25_01.23.10-server.txt)
[crash-2019-01-25_01.46.15-server.txt](https://github.com/BobMowzie/MowziesMobs/files/2794964/crash-2019-01-25_01.46.15-server.txt)

**Comment by ProsperCraft** [comment]
My dedicated server running Ancient TownCraft modpack locked hard - here is the warmroast results.

![8b6cb19af7404172fabc568d7431d9ec](https://user-images.githubusercontent.com/4427684/52168019-a177f080-26e1-11e9-904a-eecfc087edfc.png)

**Comment by ProsperCraft** [comment]
Here are the stall reports from the sampler mod.

[stall-2019-02-02_12.07.10-3.txt](https://github.com/BobMowzie/MowziesMobs/files/2824753/stall-2019-02-02_12.07.10-3.txt)
[stall-2019-02-02_12.11.11-4.txt](https://github.com/BobMowzie/MowziesMobs/files/2824754/stall-2019-02-02_12.11.11-4.txt)
[stall-2019-02-02_12.19.12-5.txt](https://github.com/BobMowzie/MowziesMobs/files/2824755/stall-2019-02-02_12.19.12-5.txt)
[stall-2019-02-02_12.35.13-6.txt](https://github.com/BobMowzie/MowziesMobs/files/2824756/stall-2019-02-02_12.35.13-6.txt)
[stall-2019-02-02_13.07.14-7.txt](https://github.com/BobMowzie/MowziesMobs/files/2824757/stall-2019-02-02_13.07.14-7.txt)
[stall-2019-02-02_07.00.30-8.txt](https://github.com/BobMowzie/MowziesMobs/files/2824758/stall-2019-02-02_07.00.30-8.txt)
[stall-2019-02-02_09.08.32-9.txt](https://github.com/BobMowzie/MowziesMobs/files/2824759/stall-2019-02-02_09.08.32-9.txt)
[stall-2019-02-02_12.03.37.txt](https://github.com/BobMowzie/MowziesMobs/files/2824760/stall-2019-02-02_12.03.37.txt)
[stall-2019-02-02_12.04.08-1.txt](https://github.com/BobMowzie/MowziesMobs/files/2824761/stall-2019-02-02_12.04.08-1.txt)
[stall-2019-02-02_12.05.09-2.txt](https://github.com/BobMowzie/MowziesMobs/files/2824762/stall-2019-02-02_12.05.09-2.txt)

**Comment by BobMowzie** [comment]
Alright. I can't find a proper fix, but from these reports I have determined its caused by the navigation AI. No idea why, seeing as it's copied directly from ghasts.
I have disabled lantern navigation as a temporary fix. Instead, they'll just float up and down in roughly the same spot. They'll still be a nice ambient mob even if they can't wander.
