### ISSUE TITLE
Dedicated Server Crash with Naga

### ISSUE THREAD

**Issue by naqaden** [BobMowzie/MowziesMobs#121]
Nagas run client code on servers.
<details>
<summary>Error:</summary><p>

```
[Server thread/ERROR] [FML]: Encountered an exception while constructing entity 'mowziesmobs:naga'
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
        at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:305) [EntityEntryBuilder$ConstructorFactory.class:?]
        at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:291) [EntityEntryBuilder$ConstructorFactory.class:?]
        at net.minecraftforge.fml.common.registry.EntityEntry.newInstance(EntityEntry.java:68) [EntityEntry.class:?]
        at net.minecraft.world.biome.Biome$SpawnListEntry.newInstance(Biome.java:655) [anh$c.class:?]
        at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:141) [anb.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: net/ilexiconn/llibrary/client/model/tools/ControlledAnimation
     >  at com.bobmowzie.mowziesmobs.server.entity.naga.EntityNaga.<init>(EntityNaga.java:67) ~[EntityNaga.class:?]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: net.ilexiconn.llibrary.client.model.tools.ControlledAnimation
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        at com.bobmowzie.mowziesmobs.server.entity.naga.EntityNaga.<init>(EntityNaga.java:67) ~[EntityNaga.class:?]
        ... 15 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@53093491 from coremod FMLCorePlugin
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) ~[forge-1.12.2-14.23.5.2807-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        at com.bobmowzie.mowziesmobs.server.entity.naga.EntityNaga.<init>(EntityNaga.java:67) ~[EntityNaga.class:?]
        ... 15 more
Caused by: java.lang.RuntimeException: Attempted to load class net/ilexiconn/llibrary/client/model/tools/ControlledAnimation for invalid side SERVER
        at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[forge-1.12.2-14.23.5.2807-universal.jar:?]
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge-1.12.2-14.23.5.2807-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        at com.bobmowzie.mowziesmobs.server.entity.naga.EntityNaga.<init>(EntityNaga.java:67) ~[EntityNaga.class:?]
        ... 15 more
```
</p></details>

**Comment by SirAron111** [comment]
https://pastebin.com/cq0VhSzP yep can confirm naga crashes lantern crashes to something is strange here

**Comment by CatHams** [comment]
I also have crashes when entering into biomes where naga and lanterns spawn, and on top of that the naga refuses to spawn on a server I run through aternos, even with commands and eggs.
seems like I'm not the only one with the first issue.

**Comment by SirAron111** [comment]
If the crash from naga is the same wander around ai as for lantern than just make them sit on a rock or have them spawn as a structure mob like your other mobs (like in on a nest on mountain tops) until a player gets in agro range I actually like your mobs being in structures a lot make the fights worth wile and fun not like random zombies everywhere

**Comment by BobMowzie** [comment]
It’s not it’s totally unrelated. I fixed it properly.
