### ISSUE TITLE
Naga Spawning still crashes Server

### ISSUE THREAD

**Issue by Mario90900** [BobMowzie/MowziesMobs#126]
I've been dealing with that Naga issue from 1.5.2 for a few days now, and noticed that even after updating the mod to 1.5.3, the Naga are still crashing the server when they attempt to spawn. In the debug log it shows that it attempted to spawn a Naga, then the following error popped up.

https://pastebin.com/NuhXjsXv

It seems like the mob fails to create, leaving it null, and then the game does not null check if it has a mob or not before attempting to spawn it, crashing the server and leaving a possibly unhelpful crash log. It can be found at the following link if you do end up needing it.

https://pastebin.com/HNVUhWPp

I hope this helps you figure out the issue! I really love your mobs, so I would really enjoy playing with more of them!

**Comment by bluelightning32** [comment]
I'm running a Dungeons, Dragons, and Space Shuttles server, version 1.45a. It contains MoziesMobs version 1.5.3. I hit this bug twice in a couple hours:
```
[00:40:20] [Server thread/ERROR] [FML]: Encountered an exception while constructing entity 'mowziesmobs:naga'
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
        at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:305) [EntityEntryBuilder$ConstructorFactory.class:?]
        at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:291) [EntityEntryBuilder$ConstructorFactory.class:?]
        at net.minecraftforge.fml.common.registry.EntityEntry.newInstance(EntityEntry.java:68) [EntityEntry.class:?]
        at net.minecraft.world.biome.Biome$SpawnListEntry.newInstance(Biome.java:655) [anh$c.class:?]
        at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:141) [anb.class:?]
        at net.minecraft.world.WorldServer.tick(WorldServer.java:203) [oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NoSuchFieldError: dc
        at com.bobmowzie.mowziesmobs.server.entity.naga.EntityNaga.<init>(EntityNaga.java:223) ~[EntityNaga.class:?]
        ... 15 more
```

```
[00:40:20] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:762) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:149) ~[anb.class:?]
        at net.minecraft.world.WorldServer.tick(WorldServer.java:203) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) ~[MinecraftServer.class:?]
        ... 4 more
```

**Comment by lordfriend** [comment]
When I was in an abandoned mine, some times this error occurred and the server crashed.
[crash-2019-02-26_14.56.49-server.txt](https://github.com/BobMowzie/MowziesMobs/files/2906080/crash-2019-02-26_14.56.49-server.txt)

**Comment by jonathan-wideman** [comment]
I'm having this issue on 1.5.3 as well, running the Rouguelike Adventures and Dungeons modpack on a dedicated server. The **server** crashes when attempting to spawn a naga with the same error message as the OP.

**Comment by BobMowzie** [comment]
This issue is closed because it has been fixed. The update containing this fixed will be released soon. Please disable nagas using the config file in the meantime.
