### ISSUE TITLE
Geomancy dig doesn't appear to work on servers.

### ISSUE THREAD

**Issue by rfwainug** [BobMowzie/MowziesMobs#127]
net.minecraft.util.ReportedException: Ticking player at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?] at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?] at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?] at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?] at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.NoSuchMethodError: net/minecraft/entity/player/EntityPlayer.func_70016_h(DDD)V (loaded from jar:file:/home/minecraft/servers/mine242876/minecraft_server.1.12.2.jar!/aed.class by net.minecraft.launchwrapper.LaunchClassLoader@49d7d4fa) called from class com.bobmowzie.mowziesmobs.server.property.power.PowerGeomancy (loaded from jar:file:/home/minecraft/servers/mine242876/./mods/EvilNotchLib-1.2.3-PreRelease4.jar!/com/bobmowzie/mowziesmobs/server/property/power/PowerGeomancy.class by net.minecraft.launchwrapper.LaunchClassLoader@49d7d4fa). at com.bobmowzie.mowziesmobs.server.property.power.PowerGeomancy.onUpdate(PowerGeomancy.java:84) ~[PowerGeomancy.class:?] at com.bobmowzie.mowziesmobs.server.ServerEventHandler.onPlayerTick(ServerEventHandler.java:288) ~[ServerEventHandler.class:?] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_602_ServerEventHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?] at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?] at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370) ~[FMLCommonHandler.class:?] at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378) ~[aed.class:?] at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[aed.class:?] at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]

**Comment by rfwainug** [comment]
As for "EvilNotchLib-1.2.3-PreRelease4.jar!" I renamed your mod to avoid players searching up and learning about the mods used on the server.
