### ISSUE TITLE
Sun Blessing achievement  not working

### ISSUE THREAD

**Issue by V-Boy** [BobMowzie/MowziesMobs#227]
`[17:26:59] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement mowziesmobs:suns_blessing
com.google.gson.JsonSyntaxException: Unknown effect 'mowziesmobs:suns_blessing'
	at net.minecraft.advancements.critereon.MobEffectsPredicate.deserialize(SourceFile:70) ~[at.class:?]
	at net.minecraft.advancements.critereon.EffectsChangedTrigger.deserializeInstance(SourceFile:54) ~[ae.class:?]
	at net.minecraft.advancements.critereon.EffectsChangedTrigger.deserializeInstance(SourceFile:17) ~[ae.class:?]
	at net.minecraft.advancements.Criterion.criterionFromJson(SourceFile:35) ~[n.class:?]
	at net.minecraft.advancements.Criterion.criteriaFromJson(SourceFile:46) ~[n.class:?]
	at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:204) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:517) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:537) ~[rc.class:?]
	at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1381) ~[ForgeHooks.class:14.23.5.2854]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) [CraftingHelper.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1359) [ForgeHooks.class:14.23.5.2854]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1326) [ForgeHooks.class:14.23.5.2854]
	at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:69) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.init(WorldServer.java:156) [oo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:133) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:233) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]`

**Comment by BobMowzie** [comment]
Do you have any other mods installed?

**Comment by V-Boy** [comment]
I do infact, a lot. Not sure what could be causing it though.

**Comment by pau101** [comment]
Fixed by resolution of #243
