### ISSUE TITLE
Barako spawns in nether

### ISSUE THREAD

**Issue by SiberiusElBoa** [BobMowzie/MowziesMobs#229]
Every time i start the server and i join the server it crashes instantly, here´s the crash report

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2020-06-07 15:44:34 CEST
Description: Ticking entity

java.lang.NullPointerException
    at com.oblivioussp.spartanweaponry.event.EventHandlerCommon.onLootLevel(EventHandlerCommon.java:218)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_599_EventHandlerCommon_onLootLevel_LootingLevelEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:647)
    at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:639)
    at net.minecraft.world.storage.loot.LootContext.getLootingModifier(LootContext.java:99)
    at net.minecraft.world.storage.loot.conditions.RandomChanceWithLooting.testCondition(RandomChanceWithLooting.java:26)
    at net.minecraft.world.storage.loot.conditions.LootConditionManager.testAllConditions(LootConditionManager.java:49)
    at net.minecraft.world.storage.loot.LootPool.generateLoot(LootPool.java:77)
    at net.minecraft.world.storage.loot.LootTable.generateLootForPools(LootTable.java:42)
    at net.minecraft.entity.EntityLiving.dropLoot(EntityLiving.java:541)
    at com.bobmowzie.mowziesmobs.server.entity.MowzieEntity.onDeathUpdate(MowzieEntity.java:377)
    at com.bobmowzie.mowziesmobs.server.entity.MowzieEntity.onEntityUpdate(MowzieEntity.java:358)
    at net.minecraft.entity.Entity.onUpdate(Entity.java:389)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2096)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295)
    at com.bobmowzie.mowziesmobs.server.entity.MowzieEntity.onUpdate(MowzieEntity.java:175)
    at com.bobmowzie.mowziesmobs.server.entity.barakoa.EntityBarakoa.onUpdate(EntityBarakoa.java:216)
    at com.bobmowzie.mowziesmobs.server.entity.barakoa.EntityBarakoaya.onUpdate(EntityBarakoaya.java:131)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$zzj000$updateEntity(World.java:4123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: mowziesmobs:barakoaya (com.bobmowzie.mowziesmobs.server.entity.barakoa.EntityBarakoaya)
  Entity ID: 63291
  Entity Name: Barakoa
  Entity's Exact location: 1080.25, 84.00, -231.85
  Entity's Block location: World: (1080,84,-232), Chunk: (at 8,5,8 in 67,-15; contains blocks 1072,0,-240 to 1087,255,-225), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:187,ForgeData:{"scalinghealth:difficulty":30s},Attributes:[{Base:-2.0d,Name:"tc.mobmod"},{Base:0.0d,Name:"tc.mobmodtaint"},{Base:0.0d,Name:"generic.scales"},{Base:10.0d,Modifiers:[{UUIDMost:-4557935957806527035L,UUIDLeast:-4950522221421205810L,Amount:0.9549751281738281d,Operation:1,Name:"ScalingHealth.HealthModifier"}],Name:"generic.maxHealth"},{Base:1.0d,Name:"generic.knockbackResistance"},{Base:0.699999988079071d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:16.0d,Modifiers:[{UUIDMost:-2124345827014655902L,UUIDLeast:-4741569139731637345L,Amount:-0.04177951506071565d,Operation:1,Name:"Random spawn bonus"}],Name:"generic.followRange"},{Base:2.0d,Modifiers:[{UUIDMost:-3218372695593237220L,UUIDLeast:-8743736172551149415L,Amount:1.7925390005111694d,Operation:0,Name:"ScalingHealth.DamageModifier"}],Name:"generic.attackDamage"}],Invulnerable:0b,FallFlying:0b,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,weapon:0,DeathTime:52s,ForgeCaps:{"llibrary:extendedentitydatacapability":{"mm:living":{frozenYaw:0.0f,freezeProgress:0.0f,frozenPitch:0.0f,prevHasAI:0b,frozenYawHead:0.0f,frozenEntityID:-1,frozenLimbSwingAmount:0.0f,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f}},"twilightforest:cap_shield":{permshields:0,tempshields:0},"vampirism:iextendedcreature":{maxBlood:-1,poisonousBlood:0b,bloodLevel:-1}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,mask:1,Motion:[0.0d,-0.0784000015258789d,0.0d],Leashed:0b,UUIDLeast:-7602516931793788962L,Health:0.0f,LeftHanded:0b,Air:300s,OnGround:1b,Dimension:-1,Rotation:[186.14241f,-25.600842f],UpdateBlocked:0b,HandItems:[{},{}],timeOffering:13982,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],UUIDMost:2815372540612002133L,Pos:[1080.2466876783733d,84.0d,-231.84730450584345d],offeringTrade:{output:{id:"mowziesmobs:painted_acacia",Count:2b,Damage:0s},input:{id:"minecraft:gold_nugget",Count:1b,Damage:0s},weight:4},Fire:-1s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s,tradeStore:{trades:[{output:{ForgeCaps:{"astralsorcery:cap_item_amulet_holder":{}},id:"mowziesmobs:blowgun",Count:1b,Damage:0s},input:{id:"minecraft:gold_nugget",Count:5b,Damage:0s},weight:6},{output:{id:"mowziesmobs:dart",Count:8b,Damage:0s},input:{id:"minecraft:dye",Count:10b,Damage:3s},weight:6},{output:{ForgeCaps:{"astralsorcery:cap_item_amulet_holder":{}},id:"mowziesmobs:spear",Count:1b,Damage:0s},input:{id:"minecraft:gold_nugget",Count:5b,Damage:0s},weight:4},{output:{id:"mowziesmobs:painted_acacia",Count:2b,Damage:0s},input:{id:"minecraft:gold_nugget",Count:1b,Damage:0s},weight:4},{output:{id:"mowziesmobs:painted_acacia",Count:1b,Damage:0s},input:{id:"minecraft:dye",Count:16b,Damage:3s},weight:4},{output:{id:"minecraft:cooked_chicken",Count:2b,Damage:0s},input:{id:"minecraft:dye",Count:10b,Damage:3s},weight:2},{output:{id:"minecraft:cooked_chicken",Count:1b,Damage:0s},input:{id:"minecraft:gold_nugget",Count:1b,Damage:0s},weight:2},{output:{id:"minecraft:cooked_porkchop",Count:2b,Damage:0s},input:{id:"minecraft:dye",Count:14b,Damage:3s},weight:2},{output:{id:"minecraft:cooked_porkchop",Count:1b,Damage:0s},input:{id:"minecraft:gold_nugget",Count:2b,Damage:0s},weight:2},{output:{id:"minecraft:gold_nugget",Count:5b,Damage:0s},input:{id:"minecraft:melon",Count:3b,Damage:0s},weight:2},{output:{id:"minecraft:gold_nugget",Count:3b,Damage:0s},input:{id:"minecraft:chicken",Count:1b,Damage:0s},weight:2},{output:{id:"minecraft:gold_ingot",Count:2b,Damage:0s},input:{ForgeCaps:{"astralsorcery:cap_item_amulet_holder":{}},id:"minecraft:iron_sword",Count:1b,Damage:0s},weight:2},{output:{id:"minecraft:gold_ingot",Count:4b,Damage:0s},input:{ForgeCaps:{"astralsorcery:cap_item_amulet_holder":{}},id:"minecraft:iron_helmet",Count:1b,Damage:0s},weight:2},{output:{id:"minecraft:gold_nugget",Count:7b,Damage:0s},input:{ForgeCaps:{"astralsorcery:cap_item_amulet_holder":{}},id:"minecraft:stone_sword",Count:1b,Damage:0s},weight:2}]}}

**Comment by BobMowzie** [comment]
This is an issue with the Spartan Weaponry mod not checking a null case in their onLootLevel event. Please report this issue to the Spartan Weaponry developers.

**Comment by Mofo50C** [comment]
the crash is from spartan weaponry but why are the barakoas spawning in the nether im having this issue as well

**Comment by BobMowzie** [comment]
Oh wait this is two separate issues.
Did you check the config at all? Is it just the villages or hunting packs too?
