### ISSUE TITLE
Parsing error loading built-in advancement (Suns_blessing)

### ISSUE THREAD

**Issue by madmax3004** [BobMowzie/MowziesMobs#236]
MC Version: 1.12.2
Forge Version: 14.23.5.2854
MowziesMobs Version: 1.5.6

Error:

`[22:56:40] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement mowziesmobs:suns_blessing
com.google.gson.JsonSyntaxException: Unknown effect 'mowziesmobs:suns_blessing'
        at net.minecraft.advancements.critereon.MobEffectsPredicate.deserialize(SourceFile:70) ~[at.class:?]
        at net.minecraft.advancements.critereon.EffectsChangedTrigger.deserializeInstance(SourceFile:54) ~[ae.class:?]
        at net.minecraft.advancements.critereon.EffectsChangedTrigger.deserializeInstance(SourceFile:17) ~[ae.class:?]
        at net.minecraft.advancements.Criterion.criterionFromJson(SourceFile:35) ~[n.class:?]
        at net.minecraft.advancements.Criterion.criteriaFromJson(SourceFile:46) ~[n.class:?]
        at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:204) ~[i$a.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:517) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:537) ~[rc.class:?]
        at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1381) ~[ForgeHooks.class:14.23.5.2854]
        at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) [CraftingHelper.class:?]
        at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1359) [ForgeHooks.class:14.23.5.2854]
        at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1326) [ForgeHooks.class:14.23.5.2854]
        at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:69) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
        at net.minecraft.world.WorldServer.init(WorldServer.java:156) [oo.class:?]
        at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:298) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

**Comment by madmax3004** [comment]
Second error later in the logs:

`[22:56:49] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement mowziesmobs:suns_blessing
com.google.gson.JsonSyntaxException: Unknown effect 'mowziesmobs:suns_blessing'
        at net.minecraft.advancements.critereon.MobEffectsPredicate.deserialize(SourceFile:70) ~[at.class:?]
        at net.minecraft.advancements.critereon.EffectsChangedTrigger.deserializeInstance(SourceFile:54) ~[ae.class:?]
        at net.minecraft.advancements.critereon.EffectsChangedTrigger.deserializeInstance(SourceFile:17) ~[ae.class:?]
        at net.minecraft.advancements.Criterion.criterionFromJson(SourceFile:35) ~[n.class:?]
        at net.minecraft.advancements.Criterion.criteriaFromJson(SourceFile:46) ~[n.class:?]
        at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:204) ~[i$a.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:517) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:537) ~[rc.class:?]
        at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1381) ~[ForgeHooks.class:14.23.5.2854]
        at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) [CraftingHelper.class:?]
        at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1359) [ForgeHooks.class:14.23.5.2854]
        at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1326) [ForgeHooks.class:14.23.5.2854]
        at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:69) [ns.class:?]
        at net.minecraft.server.MinecraftServer.reload(MinecraftServer.java:1429) [MinecraftServer.class:?]
        at com.feed_the_beast.ftblib.lib.data.FTBLibAPI.reloadServer(FTBLibAPI.java:105) [FTBLibAPI.class:?]
        at com.feed_the_beast.ftblib.lib.data.Universe.load(Universe.java:517) [Universe.class:?]
        at com.feed_the_beast.ftblib.lib.data.Universe.onServerStarted(Universe.java:128) [Universe.class:?]
        at com.feed_the_beast.ftblib.FTBLib.onServerStarted(FTBLib.java:120) [FTBLib.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:804) [Loader.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:302) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

**Comment by BobMowzie** [comment]
Duplicate #227
