### ISSUE TITLE
Entity Crash

### ISSUE THREAD

**Issue by dazadazu** [BobMowzie/MowziesMobs#274]
Odd crash, can't figure out how to solve it. Latest version on minecraft 1.12.

[crash-2020-11-08_00.09.34-server (2).txt](https://github.com/BobMowzie/MowziesMobs/files/5506092/crash-2020-11-08_00.09.34-server.2.txt)

// Ouch. That hurt :(

Time: 11/8/20 12:09 AM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:149)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

**Comment by BobMowzie** [comment]
I don’t see any indication here that this is a Mowzie’s Mobs related crash.

**Comment by dazadazu** [comment]
No I'm not. I was just told that this was a common crash for MM I've long since temp removed it and I've been removing mods that spawn mobs all night. Sorry for making an issue.

**Comment by BobMowzie** [comment]
No need to apologize!
Very strange, I’ve never seen this before. Who told you this was MM? Did they say why?

**Comment by dazadazu** [comment]
Bisecthositing and no, just referred to this mod. I think I found the culprit considering it took all night and I've yet to crash. But I think it's the mod called "Harvester Night - tweaked edition for the Rebirth of the night modpack"

**Comment by BobMowzie** [comment]
Ah, okay.
