### ISSUE TITLE
Incompatible with Epic fight mod (sort of)

### ISSUE THREAD

**Issue by manmanguy** [BobMowzie/MowziesMobs#318]
I've been using the two mods to create a soft of high risk, high reward gameplay style. I was fine with the weapons just acting as swords or blocks. Until I beat the Knight. I used his axe, no animations for special moves. I was totally fine with it. Tried placing on the helmet, then went into the third person mode epic fight mod has. And the game crashes, I'm pretty sure it's how the armor and helmet is rendered by the multi-limb body. As various other mods have similar issues, where some stuff is displaced, or a visor is missing, but don't generally crash when i try wearing an armor piece. (i've also tried the sun mask, it crashes too), It isn't game breaking or anything. Just slightly annoying that I can't use any armor pieces.

**Comment by BobMowzie** [comment]
Can you please post the crash log?

**Comment by manmanguy** [comment]
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at com.epicfight.capabilities.item.ArmorCapability.getBipedArmorModel(ArmorCapability.java:39)
	at com.epicfight.client.renderer.layer.EquipmentRenerer.render(EquipmentRenerer.java:77)
	at com.epicfight.client.renderer.entity.RenderBiped.renderLayer(RenderBiped.java:42)
	at com.epicfight.client.renderer.entity.RenderArmatureEntity.renderModel(RenderArmatureEntity.java:97)
	at com.epicfight.client.renderer.entity.RenderPlayerMod.doRender(RenderPlayerMod.java:30)
	at com.epicfight.client.renderer.entity.RenderPlayerMod.doRender(RenderPlayerMod.java:13)
	at com.epicfight.client.renderer.ModRenderManager.renderEntityArmatureModel(ModRenderManager.java:131)
	at com.epicfight.client.events.RenderEvents.renderLivingEvent(RenderEvents.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_39_RenderEvents_renderLivingEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.call(Reflector.java:976)
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1251)
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1237)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:114)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:71)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:413)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:393)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:850)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1808)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.epicfight.capabilities.item.ArmorCapability.getBipedArmorModel(ArmorCapability.java:39)
	at com.epicfight.client.renderer.layer.EquipmentRenerer.render(EquipmentRenerer.java:77)
	at com.epicfight.client.renderer.entity.RenderBiped.renderLayer(RenderBiped.java:42)
	at com.epicfight.client.renderer.entity.RenderArmatureEntity.renderModel(RenderArmatureEntity.java:97)
	at com.epicfight.client.renderer.entity.RenderPlayerMod.doRender(RenderPlayerMod.java:30)
	at com.epicfight.client.renderer.entity.RenderPlayerMod.doRender(RenderPlayerMod.java:13)
	at com.epicfight.client.renderer.ModRenderManager.renderEntityArmatureModel(ModRenderManager.java:131)
	at com.epicfight.client.events.RenderEvents.renderLivingEvent(RenderEvents.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_39_RenderEvents_renderLivingEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.call(Reflector.java:976)
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1251)
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1237)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:114)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:71)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)

-- Entity being rendered --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 2309
	Entity Name: Pothatman
	Entity's Exact location: 221.83, 83.00, 267.49
	Entity's Block location: World: (221,83,267), Chunk: (at 13,5,11 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderPlayer@2974d805
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 28.199968
	Delta: 0.039986372
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:413)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:393)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:850)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1808)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Pothatman'/2309, l='MpServer', x=221.83, y=83.00, z=267.49]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (236,64,252), Chunk: (at 12,4,12 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 515 game time, 515 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 129 total; [EntityCreeper['Creeper'/2563, l='MpServer', x=192.50, y=39.00, z=308.50], EntitySlime['Slime'/2310, l='MpServer', x=174.37, y=24.02, z=225.20], EntitySpider['Spider'/2314, l='MpServer', x=152.50, y=45.00, z=204.50], EntitySpider['Spider'/2316, l='MpServer', x=172.50, y=26.00, z=264.50], EntityBat['Bat'/2320, l='MpServer', x=162.74, y=17.14, z=277.30], EntityBat['Bat'/2321, l='MpServer', x=160.73, y=44.23, z=258.58], EntityZombie['Zombie'/2323, l='MpServer', x=143.50, y=26.00, z=208.50], EntityZombie['Zombie'/2324, l='MpServer', x=155.50, y=30.00, z=223.50], EntityCreeper['Creeper'/2325, l='MpServer', x=149.50, y=28.00, z=294.50], EntitySkeleton['Skeleton'/2328, l='MpServer', x=171.50, y=24.00, z=260.50], EntityEnderman['Enderman'/2329, l='MpServer', x=169.50, y=25.00, z=246.50], EntityCreeper['Creeper'/2330, l='MpServer', x=157.50, y=30.00, z=227.50], EntityCreeper['Creeper'/2586, l='MpServer', x=191.50, y=39.00, z=310.50], EntityCreeper['Creeper'/2587, l='MpServer', x=216.56, y=40.00, z=208.07], EntityZombie['Zombie'/2588, l='MpServer', x=224.50, y=39.00, z=201.50], EntityZombie['Zombie'/2589, l='MpServer', x=224.50, y=39.00, z=202.50], EntityZombie['Zombie'/2334, l='MpServer', x=164.50, y=37.00, z=235.50], EntityPlayerSP['Pothatman'/2309, l='MpServer', x=221.83, y=83.00, z=267.49], EntityBat['Bat'/2341, l='MpServer', x=159.19, y=49.99, z=266.41], EntityChicken['Chicken'/76, l='MpServer', x=150.50, y=71.00, z=212.50], EntityChicken['Chicken'/77, l='MpServer', x=150.56, y=72.00, z=211.50], EntityChicken['Chicken'/78, l='MpServer', x=147.50, y=73.00, z=210.50], EntityChicken['Chicken'/79, l='MpServer', x=150.50, y=73.00, z=209.48], EntityChicken['Chicken'/80, l='MpServer', x=143.64, y=77.00, z=302.86], EntityChicken['Chicken'/81, l='MpServer', x=149.50, y=75.00, z=304.50], EntityChicken['Chicken'/82, l='MpServer', x=148.50, y=76.00, z=302.50], EntityChicken['Chicken'/83, l='MpServer', x=148.50, y=76.00, z=302.50], EntityChicken['Chicken'/88, l='MpServer', x=162.50, y=66.00, z=225.50], EntityChicken['Chicken'/89, l='MpServer', x=163.50, y=67.00, z=221.50], EntityChicken['Chicken'/90, l='MpServer', x=164.50, y=66.00, z=225.50], EntityChicken['Chicken'/91, l='MpServer', x=166.50, y=66.00, z=226.50], EntityChicken['Chicken'/92, l='MpServer', x=162.50, y=63.00, z=281.50], EntityChicken['Chicken'/93, l='MpServer', x=160.50, y=63.00, z=281.50], EntityChicken['Chicken'/94, l='MpServer', x=162.50, y=63.00, z=280.50], EntityChicken['Chicken'/95, l='MpServer', x=162.50, y=63.00, z=280.50], EntityCow['Cow'/108, l='MpServer', x=182.50, y=64.00, z=270.50], EntityCow['Cow'/109, l='MpServer', x=180.50, y=64.00, z=272.50], EntityCow['Cow'/110, l='MpServer', x=181.47, y=65.00, z=276.15], EntityCow['Cow'/111, l='MpServer', x=177.50, y=64.00, z=273.50], EntitySheep['Sheep'/112, l='MpServer', x=171.50, y=65.00, z=273.50], EntitySheep['Sheep'/113, l='MpServer', x=172.24, y=65.00, z=267.34], EntitySheep['Sheep'/114, l='MpServer', x=171.50, y=66.00, z=271.50], EntityBat['Bat'/2418, l='MpServer', x=161.48, y=29.71, z=236.81], EntitySheep['Sheep'/115, l='MpServer', x=174.50, y=65.00, z=270.50], EntityBat['Bat'/2419, l='MpServer', x=169.40, y=28.65, z=233.65], EntityCreeper['Creeper'/2421, l='MpServer', x=149.50, y=56.00, z=239.50], EntityBat['Bat'/2422, l='MpServer', x=169.16, y=27.34, z=256.80], EntityBat['Bat'/2423, l='MpServer', x=158.71, y=27.64, z=250.71], EntityBat['Bat'/2424, l='MpServer', x=168.38, y=32.76, z=220.25], EntityBat['Bat'/2425, l='MpServer', x=164.25, y=32.00, z=222.66], EntityBat['Bat'/2426, l='MpServer', x=142.31, y=35.00, z=205.51], EntityChicken['Chicken'/124, l='MpServer', x=186.50, y=68.00, z=239.50], EntityZombieVillager['Zombie Villager'/2428, l='MpServer', x=164.50, y=44.00, z=254.50], EntityChicken['Chicken'/125, l='MpServer', x=184.50, y=68.00, z=236.50], EntityBat['Bat'/2429, l='MpServer', x=147.21, y=39.56, z=335.16], EntityChicken['Chicken'/126, l='MpServer', x=187.50, y=68.00, z=242.50], EntityBat['Bat'/2430, l='MpServer', x=149.62, y=39.93, z=340.62], EntityChicken['Chicken'/127, l='MpServer', x=190.50, y=69.00, z=243.50], EntityBat['Bat'/2431, l='MpServer', x=147.46, y=39.07, z=336.07], EntityChicken['Chicken'/128, l='MpServer', x=190.50, y=69.00, z=258.50], EntityBat['Bat'/2432, l='MpServer', x=147.36, y=39.76, z=338.52], EntityChicken['Chicken'/129, l='MpServer', x=186.50, y=69.00, z=257.50], EntityChicken['Chicken'/130, l='MpServer', x=184.84, y=67.00, z=264.41], EntityChicken['Chicken'/131, l='MpServer', x=192.50, y=69.00, z=257.50], EntityChicken['Chicken'/132, l='MpServer', x=185.50, y=66.00, z=267.50], EntityZombie['Zombie'/2436, l='MpServer', x=176.50, y=36.00, z=300.50], EntityChicken['Chicken'/133, l='MpServer', x=188.50, y=67.00, z=269.50], EntitySpider['Spider'/2437, l='MpServer', x=166.50, y=58.00, z=280.50], EntityChicken['Chicken'/134, l='MpServer', x=187.50, y=67.00, z=271.50], EntityChicken['Chicken'/135, l='MpServer', x=191.50, y=67.00, z=270.50], EntitySkeleton['Skeleton'/2441, l='MpServer', x=172.50, y=26.00, z=261.50], EntitySkeleton['Skeleton'/2442, l='MpServer', x=150.50, y=28.00, z=294.50], EntitySkeleton['Skeleton'/2444, l='MpServer', x=154.50, y=27.00, z=245.50], EntityZombie['Zombie'/2446, l='MpServer', x=161.50, y=54.00, z=273.50], EntityZombie['Zombie'/2448, l='MpServer', x=154.50, y=24.00, z=262.50], EntityChicken['Chicken'/147, l='MpServer', x=225.27, y=72.00, z=206.84], EntityChicken['Chicken'/148, l='MpServer', x=221.50, y=71.00, z=212.50], EntityChicken['Chicken'/149, l='MpServer', x=222.50, y=71.00, z=210.50], EntityChicken['Chicken'/150, l='MpServer', x=215.47, y=72.00, z=210.81], EntitySkeleton['Skeleton'/2464, l='MpServer', x=174.50, y=37.00, z=295.50], EntityCreeper['Creeper'/2465, l='MpServer', x=170.50, y=25.00, z=193.50], EntitySkeleton['Skeleton'/2468, l='MpServer', x=168.50, y=32.00, z=212.50], EntityChicken['Chicken'/167, l='MpServer', x=228.62, y=71.00, z=234.10], EntitySkeleton['Skeleton'/2471, l='MpServer', x=169.50, y=32.00, z=215.50], EntityChicken['Chicken'/168, l='MpServer', x=237.50, y=69.00, z=224.50], EntityChicken['Chicken'/169, l='MpServer', x=237.50, y=70.00, z=225.50], EntityChicken['Chicken'/170, l='MpServer', x=235.50, y=69.00, z=224.50], EntityPig['Pig'/171, l='MpServer', x=236.50, y=72.00, z=238.50], EntityPig['Pig'/172, l='MpServer', x=230.45, y=71.00, z=242.55], EntityPig['Pig'/173, l='MpServer', x=224.20, y=70.00, z=237.55], EntityCreeper['Creeper'/2477, l='MpServer', x=169.30, y=25.00, z=241.10], EntityPig['Pig'/174, l='MpServer', x=243.74, y=70.00, z=232.18], EntityZombie['Zombie'/2478, l='MpServer', x=169.42, y=25.00, z=243.15], EntityZombie['Zombie'/2479, l='MpServer', x=163.57, y=28.00, z=240.81], EntitySkeleton['Skeleton'/2485, l='MpServer', x=166.53, y=45.00, z=241.29], EntityChicken['Chicken'/182, l='MpServer', x=259.20, y=76.00, z=255.73], EntityChicken['Chicken'/183, l='MpServer', x=255.46, y=78.00, z=255.92], EntityChicken['Chicken'/184, l='MpServer', x=267.50, y=73.00, z=262.12], EntitySkeleton['Skeleton'/2488, l='MpServer', x=158.50, y=27.00, z=218.50], EntityChicken['Chicken'/185, l='MpServer', x=267.94, y=72.00, z=250.50], EntityFallingBlock['Falling Block'/698, l='MpServer', x=240.50, y=14.59, z=161.50], EntitySheep['Sheep'/186, l='MpServer', x=245.46, y=86.06, z=263.69], EntitySheep['Sheep'/187, l='MpServer', x=238.45, y=84.00, z=260.62], EntitySheep['Sheep'/188, l='MpServer', x=255.50, y=81.00, z=264.27], EntityZombie['Zombie'/2492, l='MpServer', x=153.50, y=26.00, z=260.50], EntitySheep['Sheep'/189, l='MpServer', x=246.73, y=80.00, z=256.46], EntityZombieVillager['Zombie Villager'/2493, l='MpServer', x=162.50, y=48.00, z=195.50], EntitySpider['Spider'/2496, l='MpServer', x=169.50, y=25.00, z=248.50], EntityCreeper['Creeper'/2497, l='MpServer', x=171.50, y=25.00, z=253.50], EntityChicken['Chicken'/197, l='MpServer', x=270.84, y=70.00, z=278.55], EntityChicken['Chicken'/198, l='MpServer', x=271.50, y=71.00, z=268.50], EntitySkeleton['Skeleton'/2502, l='MpServer', x=177.50, y=47.00, z=223.50], EntityChicken['Chicken'/199, l='MpServer', x=271.50, y=71.00, z=270.50], EntityChicken['Chicken'/200, l='MpServer', x=275.50, y=68.00, z=270.50], EntitySkeleton['Skeleton'/2507, l='MpServer', x=164.50, y=48.00, z=198.50], EntitySkeleton['Skeleton'/2508, l='MpServer', x=165.50, y=48.00, z=197.50], EntitySpider['Spider'/2515, l='MpServer', x=152.50, y=26.00, z=259.50], EntityMinecartChest['Minecart with Chest'/212, l='MpServer', x=286.50, y=16.06, z=206.50], EntityChicken['Chicken'/213, l='MpServer', x=291.50, y=70.00, z=203.50], EntityChicken['Chicken'/214, l='MpServer', x=293.50, y=71.00, z=206.50], EntityChicken['Chicken'/215, l='MpServer', x=293.50, y=71.00, z=209.50], EntityChicken['Chicken'/216, l='MpServer', x=293.50, y=72.00, z=210.50], EntitySheep['Sheep'/217, l='MpServer', x=279.92, y=70.00, z=213.50], EntitySheep['Sheep'/218, l='MpServer', x=280.85, y=71.00, z=213.38], EntitySheep['Sheep'/219, l='MpServer', x=281.50, y=71.00, z=211.50], EntitySheep['Sheep'/220, l='MpServer', x=279.71, y=70.00, z=214.51], EntityZombie['Zombie'/2526, l='MpServer', x=253.50, y=21.00, z=258.50], EntitySkeleton['Skeleton'/2547, l='MpServer', x=173.50, y=40.00, z=266.50], EntityCreeper['Creeper'/2558, l='MpServer', x=241.50, y=32.00, z=258.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 570683424 bytes (544 MB) / 1006632960 bytes (960 MB) up to 6476005376 bytes (6176 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx6169M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5_pre1 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                         | Version      | Source                                | Signature                                |
	|:------ |:-------------------------- |:------------ |:------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                  | 1.12.2       | minecraft.jar                         | None                                     |
	| LCHIJA | mcp                        | 9.42         | minecraft.jar                         | None                                     |
	| LCHIJA | FML                        | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                      | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | craftstudioapi             | 1.0.0        | CraftStudio-1.0.0.93-mc1.12-alpha.jar | None                                     |
	| LCHIJA | epicfight                  | 1.12.2.0     | EpicFightMod-1.12.2-1.1.0.jar         | None                                     |
	| LCHIJA | llibrary                   | 1.7.19       | llibrary-1.7.19-1.12.2.jar            | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | mowziesmobs                | 1.5.8        | mowziesmobs-1.5.8.jar                 | None                                     |
	
	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.62' Renderer: 'GeForce GTX 560M/PCIe/SSE2'
	Launched Version: ForgeOptiFine 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 560M/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.62, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5_pre1
	OptiFine Build: 20201206-232027
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 353.62
	OpenGlRenderer: GeForce GTX 560M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by BobMowzie** [comment]
This crash is on Epic Fight Mod’s side. Please report the issue to the developer.
