### ISSUE TITLE
[1.12.2] Error Registering RenderLivingEvent

### ISSUE THREAD

**Issue by naqaden** [BobMowzie/MowziesMobs#38]
```
[20:18:44] [main/INFO] [LLibrary]: TabulaModelHandler: Domain mowziesmobs has been added.
[20:18:44] [main/ERROR] [FML]: Error registering event handler: FMLMod:mowziesmobs{1.4.1} class net.minecraftforge.client.event.RenderLivingEvent public void com.bobmowzie.mowziesmobs.client.ClientEventHandler.onRenderLiving(net.minecraftforge.client.event.RenderLivingEvent)
java.lang.InstantiationException: null
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_161]
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:130) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:112) [EventBus.class:?]
>	at com.bobmowzie.mowziesmobs.client.MMModels.register(MMModels.java:55) [MMModels.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_79_MMModels_register_ModelRegistryEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) [EventBus$1.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.fireSidedRegistryEvents(FMLClientHandler.java:1096) [FMLClientHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.fireSidedRegistryEvents(FMLCommonHandler.java:758) [FMLCommonHandler.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:640) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:466) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3922) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by BobMowzie** [comment]
Do you have any other mods installed?

**Comment by naqaden** [comment]
Yes but it happens without them too, just:

LLibrary v1.7.13 and v1.7.14
MowziesMobs v1.4.1

with default configs.

**Comment by BobMowzie** [comment]
Could you please downgrade to LLibrary 1.7.9 and tell me if you still receive this error?

**Comment by naqaden** [comment]
Yep, I still receive the error.

**Comment by Rongmario** [comment]
I'm getting this too: https://paste.ee/p/qGsIZ

**Comment by naqaden** [comment]
Thanks Bob :+1:
