### ISSUE TITLE
Crash on startup. latest mod version IllegalStateException: texture not set

### ISSUE THREAD

**Issue by PrinceOfAmber** [BobMowzie/MowziesMobs#4]
I have llibrary-1.7.4-1.11.2
and mowziesmobs-1.3.2

java.lang.IllegalStateException: texture not set
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.build(UnpackedBakedQuad.java:173)
	at net.ilexiconn.llibrary.client.model.tabula.baked.VanillaTabulaModel.buildQuad(VanillaTabulaModel.java:223)
	at net.ilexiconn.llibrary.client.model.tabula.baked.VanillaTabulaModel.build(VanillaTabulaModel.java:140)
	at net.ilexiconn.llibrary.client.model.tabula.baked.VanillaTabulaModel.bake(VanillaTabulaModel.java:70)
	at pl.asie.foamfix.coremod.client.ModelLoaderParallelHelper.lambda$bake$0(ModelLoaderParallelHelper.java:54)
	at pl.asie.foamfix.coremod.client.ModelLoaderParallelHelper$$Lambda$424/1627291329.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:916)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by BobMowzie** [comment]
From the Curse page description: http://prntscr.com/f5hw9b
Identical to #1
