### ISSUE TITLE
Crash on using Axe of a Thousand Metals' slam attack

### ISSUE THREAD

**Issue by Moomallowz** [BobMowzie/MowziesMobs#546]
Threw the following error in latest.log:

[26Sep2021 14:08:48.174] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 8ec52622-6b63-4299-a747-4ef5f973cdb3
[26Sep2021 14:08:48.177] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$13159/1837424891.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at vazkii.ambience.Util.Handlers.EventHandlers.playInstant(EventHandlers.java:194) ~[?:1.16.4-1.0.1]
	at vazkii.ambience.Util.Handlers.EventHandlersServer.onPlayerAttackEvent(EventHandlersServer.java:260) ~[?:1.16.4-1.0.1]
	at net.minecraftforge.eventbus.ASMEventHandler_47_EventHandlersServer_onPlayerAttackEvent_AttackEntityEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2608/427193331.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:766) ~[?:?]
	at com.bobmowzie.mowziesmobs.server.entity.effects.EntityAxeAttack.attackTargetEntityWithCurrentItem(EntityAxeAttack.java:219) ~[?:1.5.19]
	at com.bobmowzie.mowziesmobs.server.entity.effects.EntityAxeAttack.dealDamage(EntityAxeAttack.java:173) ~[?:1.5.19]
	at com.bobmowzie.mowziesmobs.server.entity.effects.EntityAxeAttack.func_70071_h_(EntityAxeAttack.java:86) ~[?:1.5.19]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$13756/998380190.accept(Unknown Source) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 6 more

**Comment by BobMowzie** [comment]
This crash is caused by Vaskii’s ambience mod.
