### ISSUE TITLE
Exception loading structure piece with id mowziesmobs:wrought_chamber_template

### ISSUE THREAD

**Issue by xavierzzzzzz** [BobMowzie/MowziesMobs#649]
Can someone help me with this error in my minecraft 1.18.2 forge 40.1.74, it doesnt let me save a world chunk and make crashes while trying to load the chunk.

Complete log
[00:19:48] [Server thread/ERROR] [minecraft/PiecesContainer]: Exception loading structure piece with id mowziesmobs:wrought_chamber_template
java.lang.IllegalArgumentException: No enum constant net.minecraft.world.level.block.Rotation.
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?] {re:mixin}
        at net.minecraft.world.level.block.Rotation.valueOf(Rotation.java:13) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:classloading}
        at com.bobmowzie.mowziesmobs.server.world.feature.structure.WroughtnautChamberPieces$Piece.lambda$new$0(WroughtnautChamberPieces.java:36) ~[mowziesmobs-1.5.27.jar%23108!/:1.5.27] {re:classloading}
        at net.minecraft.world.level.levelgen.structure.TemplateStructurePiece.<init>(TemplateStructurePiece.java:60) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:classloading}
        at com.bobmowzie.mowziesmobs.server.world.feature.structure.WroughtnautChamberPieces$Piece.<init>(WroughtnautChamberPieces.java:36) ~[mowziesmobs-1.5.27.jar%23108!/:1.5.27] {re:classloading}
        at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.m_192753_(PiecesContainer.java:73) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:classloading}
        at net.minecraft.world.level.levelgen.feature.StructureFeature.m_191128_(StructureFeature.java:124) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.StructureFeatureAccess,pl:mixin:A}
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_188254_(ChunkSerializer.java:464) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:mixin,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinChunkSerializer,pl:mixin:APP:starlight.mixins.json:common.world.ChunkSerializerMixin,pl:mixin:A}
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_188230_(ChunkSerializer.java:196) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:mixin,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinChunkSerializer,pl:mixin:APP:starlight.mixins.json:common.world.ChunkSerializerMixin,pl:mixin:A}
        at net.minecraft.server.level.ChunkMap.m_203107_(ChunkMap.java:543) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ChunkManagerMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:securitycraft.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:542) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:classloading}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:550) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:classloading}
        at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:266) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ServerChunkProviderMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:787) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:475) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:318) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:173) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.server.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23135!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

**Comment by BobMowzie** [comment]
Unfortunately, you’ll have to wait for me to fix it. It won’t be long.

**Comment by xavierzzzzzz** [comment]
thxx
