### ISSUE TITLE
Sun's Blessing Sun Beams Causing Crash

### ISSUE THREAD

**Issue by minimurx** [BobMowzie/MowziesMobs#670]
Geckolib3 seems to run into issues while rendering in the Sun Beam impact decal while in first person. Not Sure if anyone else has run into this problem.

here is the walkthrough of the error from the crash log

Lmk if you find anything else, but I believe Geckolib3's rendering path may be the culprit.

-- Head --
Thread: Render thread
Stacktrace:
	at com.bobmowzie.mowziesmobs.client.render.entity.player.GeckoFirstPersonRenderer.setCurrentRTB(GeckoFirstPersonRenderer.java) ~[?:1.5.25] {re:classloading,pl:runtimedistcleaner:A}
	at software.bernie.geckolib3.renderers.geo.IGeoRenderer.render(IGeoRenderer.java:36) ~[?:3.0.95] {re:classloading}
	at com.bobmowzie.mowziesmobs.client.render.entity.player.GeckoFirstPersonRenderer.renderItemInFirstPerson(GeckoFirstPersonRenderer.java:84) ~[?:1.5.25] {re:classloading,pl:runtimedistcleaner:A}
	at com.bobmowzie.mowziesmobs.client.ClientEventHandler.onHandRender(ClientEventHandler.java:75) ~[?:1.5.25] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_819_ClientEventHandler_onHandRender_RenderHandEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3161/1340744662.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.renderSpecificFirstPersonHand(ForgeHooksClient.java:220) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.FirstPersonRenderer.func_228396_a_(FirstPersonRenderer.java:243) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,pl:mixin:APP:antiqueatlas-common.mixins.json:HeldItemRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228381_a_(GameRenderer.java:369) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:614) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['minimurx'/100, l='ClientLevel', x=-932.86, y=68.49, z=5898.24]]
	Chunk stats: Client Chunk Cache: 225, 90
	Level dimension: minecraft:overworld
	Level spawn location: World: (-240,86,208), Chunk: (at 0,5,0 in -15,13; contains blocks -240,0,208 to -225,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 39406 game time, 39406 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:globaldataandresourcepacks.mixins.json:ClientPackFinderMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:globaldataandresourcepacks.mixins.json:ClientPackFinderMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$495/2000603780.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

**Comment by minimurx** [comment]
Issue Resolved, but I will keep it up reguardless so when more players run into the same issue they know how to fix it.
Make sure to downgrade to Geckolib 3.0.57 link is here:
https://www.curseforge.com/minecraft/mc-mods/geckolib/files/3548338

**Comment by BobMowzie** [comment]
It says to downgrade to 3.0.57 pretty clearly on the Curseforge page, but people seem to not read it anyway. Not sure how else to tell people.
