### ISSUE TITLE
game freezes upon loading the world

### ISSUE THREAD

**Issue by InsertOriginalName** [BobMowzie/MowziesMobs#695]
I was trying to play with this mod recently but everytime I tried to load into a world the game would freeze upon reaching the "loading world..." text (Saving world instead on 1.17.1) and then it crashes with the exit code: -805306369
if anyone could help me out with this it would be appreciated.

Heres the crash log:

---- Minecraft Crash Report ----
// You're mean.

Time: 4/4/23, 7:06 PM
Description: Exception initializing level

java.lang.IllegalStateException: Unknown biome id emitted by layers: 23
	at net.minecraft.world.level.newbiome.layer.Layer.m_76715_(SourceFile:25) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading}
	at net.minecraft.world.level.biome.OverworldBiomeSource.m_7158_(OverworldBiomeSource.java:55) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading}
	at net.minecraft.world.level.biome.BiomeSource.m_7754_(SourceFile:121) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading}
	at net.minecraft.world.level.biome.BiomeSource.m_47909_(SourceFile:85) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_177896_(MinecraftServer.java:419) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:371) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:334) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:65) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:660) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.level.newbiome.layer.Layer.m_76715_(SourceFile:25) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading}
	at net.minecraft.world.level.biome.OverworldBiomeSource.m_7158_(OverworldBiomeSource.java:55) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading}
	at net.minecraft.world.level.biome.BiomeSource.m_7754_(SourceFile:121) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading}
	at net.minecraft.world.level.biome.BiomeSource.m_47909_(SourceFile:85) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_177896_(MinecraftServer.java:419) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B}
-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level name: mowzies mobs yeye
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:371) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:334) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:65) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:660) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1021979920 bytes (974 MiB) / 1476395008 bytes (1408 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 4600H with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.99
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x1636
	Graphics card #0 versionInfo: DriverVersion=27.20.15002.11002
	Graphics card #1 name: NVIDIA GeForce GTX 1650
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f99
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1278
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 15267.91
	Virtual memory used (MB): 11919.39
	Swap memory total (MB): 7726.84
	Swap memory used (MB): 863.59
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:mowziesmobs (incompatible), mod:forge, mod:geckolib3 (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE

**Comment by BobMowzie** [comment]
This error is caused by an invalid Biome ID. Mowzie's Mobs does not add any new biomes, so I do not think it is the cause of your error.

What other mods do you have installed?

**Comment by InsertOriginalName** [comment]
> This error is caused by an invalid Biome ID. Mowzie's Mobs does not add any new biomes, so I do not think it is the cause of your error.
> 
> What other mods do you have installed?

i don't have any other mods active except geckolib3.0.15

**Comment by InsertOriginalName** [comment]
sorry for late reply.
i never used datapacks along with the mod and never edited the config files.
the games freezes in every single world i play on, including new worlds.

**Comment by BobMowzie** [comment]
This is very bizarre. I can't reproduce it at all.

**Comment by BobMowzie** [comment]
The issue goes away when you uninstall mowzies mobs?

**Comment by InsertOriginalName** [comment]
> The issue goes away when you uninstall mowzies mobs?

weirdly enough no... 
i think this might just be a problem with my forge instead of the mod.
sorry for wasting your time.
