### ISSUE TITLE
my game crashes when I right click any weapon"

### ISSUE THREAD

**Issue by sorvetedaoray** [BobMowzie/MowziesMobs#704]
So I tried in a server with my friends to use the Axe of a thousand metals or something like that and the game of my friend that was with me crashed with the rmb. I tried again a little later and then my game crashed too. Then I got to a offline survival world on creative mode to test and it crashed again. Here is my crash report!
[crash-2023-06-06_22.44.44-client.txt](https://github.com/BobMowzie/MowziesMobs/files/11671810/crash-2023-06-06_22.44.44-client.txt)

**Comment by sorvetedaoray** [comment]
IDK if you need the crash text version, but here it is!

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 6/6/23 10:44 PM
Description: Rendering entity in world

java.util.NoSuchElementException: null
	at java.util.ArrayDeque.getLast(ArrayDeque.java:335) ~[?:1.8.0_51] {re:computing_frames}
	at com.mojang.blaze3d.matrix.MatrixStack.func_227860_a_(SourceFile:56) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:sodium.mixins.json:features.matrix_stack.MixinMatrixStack,pl:mixin:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:249) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.WorldRendererMixin,pl:mixin:APP:citadel.mixins.json:client.WorldRendererMixin,pl:mixin:APP:sodium.mixins.json:features.block.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:out_of_sight.mixins.json:MixinTileEntityRendererDispatcher,pl:mixin:APP:mixins.cofhcore.json:WorldRendererMixin,pl:mixin:APP:betterfpsdist.mixins.json:LevelRendererMixin,pl:mixin:APP:entityculling.mixins.json:WorldRendererMixin,pl:mixin:APP:securitycraft.mixins.json:camera.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.WorldRendererMixin,pl:mixin:APP:citadel.mixins.json:client.WorldRendererMixin,pl:mixin:APP:sodium.mixins.json:features.block.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:out_of_sight.mixins.json:MixinTileEntityRendererDispatcher,pl:mixin:APP:mixins.cofhcore.json:WorldRendererMixin,pl:mixin:APP:betterfpsdist.mixins.json:LevelRendererMixin,pl:mixin:APP:entityculling.mixins.json:WorldRendererMixin,pl:mixin:APP:securitycraft.mixins.json:camera.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.35-launcher.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$508/1999135146.call(Unknown Source) [forge-1.16.5-36.2.35-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-1.5.5.jar:1.5.5] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.ArrayDeque.getLast(ArrayDeque.java:335) ~[?:1.8.0_51] {re:computing_frames}
	at com.mojang.blaze3d.matrix.MatrixStack.func_227860_a_(SourceFile:56) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:sodium.mixins.json:features.matrix_stack.MixinMatrixStack,pl:mixin:A}
-- Entity being rendered --
Details:
	Entity Type: minecraft:horse (net.minecraft.entity.passive.horse.HorseEntity)
	Entity ID: 1027
	Entity Name: Horse
	Entity's Exact location: -146.23, 52.00, 1.29
	Entity's Block location: World: (-147,52,1), Chunk: (at 13,3,1 in -10,0; contains blocks -160,0,0 to -145,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.HorseRenderer@48476b62
	Location: -117.56,-6.86,-128.30 - World: (-118,-7,-129), Chunk: (at 10,-1,15 in -8,-9; contains blocks -128,0,-144 to -113,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: 109.6875
	Delta: 0.20003986
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:249) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.WorldRendererMixin,pl:mixin:APP:citadel.mixins.json:client.WorldRendererMixin,pl:mixin:APP:sodium.mixins.json:features.block.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:out_of_sight.mixins.json:MixinTileEntityRendererDispatcher,pl:mixin:APP:mixins.cofhcore.json:WorldRendererMixin,pl:mixin:APP:betterfpsdist.mixins.json:LevelRendererMixin,pl:mixin:APP:entityculling.mixins.json:WorldRendererMixin,pl:mixin:APP:securitycraft.mixins.json:camera.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.WorldRendererMixin,pl:mixin:APP:citadel.mixins.json:client.WorldRendererMixin,pl:mixin:APP:sodium.mixins.json:features.block.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:out_of_sight.mixins.json:MixinTileEntityRendererDispatcher,pl:mixin:APP:mixins.cofhcore.json:WorldRendererMixin,pl:mixin:APP:betterfpsdist.mixins.json:LevelRendererMixin,pl:mixin:APP:entityculling.mixins.json:WorldRendererMixin,pl:mixin:APP:securitycraft.mixins.json:camera.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['txszu'/234, l='ClientLevel', x=-32.88, y=57.00, z=129.82]]
	Chunk stats: Client Chunk Cache: 4096, 1038
	Level dimension: minecraft:overworld
	Level spawn location: World: (128,57,240), Chunk: (at 0,3,0 in 8,15; contains blocks 128,0,240 to 143,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3906 game time, 3906 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:pehkui.mixins.json:client.ClientWorldMixin,pl:mixin:APP:sodium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:sodium.mixins.json:features.world_ticking.MixinClientWorld,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.35-launcher.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$508/1999135146.call(Unknown Source) [forge-1.16.5-36.2.35-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-1.5.5.jar:1.5.5] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2930821504 bytes (2795 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xms5120m -Xmx5120m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.35-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.35-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.35-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.35-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.35-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.35
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		grounded_origins-forge-1.16.5-1.0.1.jar           |Grounded Origins              |grounded_origins              |1.0.1               |DONE      |Manifest: NOSIGNATURE
		Tabula-1.16.5-10.5.1.jar                          |Tabula                        |tabula                        |10.5.1              |DONE      |Manifest: NOSIGNATURE
		mowziesmobs-1.5.27.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.27              |DONE      |Manifest: NOSIGNATURE
		BetterDungeons-1.16.4-1.2.1.jar                   |YUNG's Better Dungeons        |betterdungeons                |1.16.4-1.2.1        |DONE      |Manifest: NOSIGNATURE
		Hats-1.16.5-10.3.4.jar                            |Hats                          |hats                          |10.3.4              |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.8.0.1009.jar                         |Just Enough Items             |jei                           |7.8.0.1009          |DONE      |Manifest: NOSIGNATURE
		Pehkui-3.7.31.16.5-forge.jar                      |Pehkui                        |pehkui                        |3.7.3+1.16.5-forge  |DONE      |Manifest: NOSIGNATURE
		simplymob-1.2.jar                                 |SimplyMob Origins (Fabric)    |simplymob                     |1.2                 |DONE      |Manifest: NOSIGNATURE
		libraryferret-forge-1.16.5-4.0.0.jar              |Library ferret                |libraryferret                 |4.0.0               |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.2.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.2      |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.5p6.jar                     |Journeymap                    |journeymap                    |5.8.5p6             |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.12.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.1              |DONE      |Manifest: NOSIGNATURE
		configured-1.5.4-1.16.5.jar                       |Configured                    |configured                    |1.5.4               |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.16.5-3.15.20.755.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.15.20.755  |DONE      |Manifest: NOSIGNATURE
		iChunUtil-1.16.5-10.7.0.jar                       |iChunUtil                     |ichunutil                     |10.7.0              |DONE      |Manifest: NOSIGNATURE
		sodium-forge-2.9.10+rev.ea6353c.jar               |SodiumReforged                |sodium                        |2.9.10+rev.ea6353c  |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.35-universal.jar                |Forge                         |forge                         |36.2.35             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Morph-1.16.5-10.2.1.jar                           |Morph                         |morph                         |10.2.1              |DONE      |Manifest: NOSIGNATURE
		out_of_sight-1.16.4-1.0.1.jar                     |Out of Sight                  |out_of_sight                  |1.16.4-1.0.1        |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.35-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		cofh_core-1.16.5-1.5.2.22.jar                     |CoFH Core                     |cofh_core                     |1.5.2.22            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_foundation-1.16.5-1.5.2.30.jar            |Thermal Series                |thermal                       |1.5.2.30            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		FarmersDelight-1.16.5-0.6.0.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.6.0        |DONE      |Manifest: NOSIGNATURE
		voicechat-forge-1.16.5-2.4.7.jar                  |Simple Voice Chat             |voicechat                     |1.16.5-2.4.7        |DONE      |Manifest: NOSIGNATURE
		thermal_innovation-1.16.5-1.5.0.4.jar             |Thermal Innovation            |thermal_innovation            |1.5.0.4             |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		BiomesOPlenty-1.16.5-13.1.0.488-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.488   |DONE      |Manifest: NOSIGNATURE
		endrem-5.0.3-R-1.16.5.jar                         |End Remastered                |endrem                        |5.0.3-R-1.16.5      |DONE      |Manifest: NOSIGNATURE
		ironfurnaces-1.16.5-2.7.7.jar                     |Iron Furnaces                 |ironfurnaces                  |2.7.7               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.2.1_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		smoothboot-forge-1.16.4-1.2.2.jar                 |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |Manifest: NOSIGNATURE
		betterfpsdist-1.2.jar                             |betterfpsdist mod             |betterfpsdist                 |1.2                 |DONE      |Manifest: NOSIGNATURE
		pirate_hats.jar                                   |Pirate Hat                    |pirate_hat                    |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.3.jar                         |Patchouli                     |patchouli                     |1.16.4-53.3         |DONE      |Manifest: NOSIGNATURE
		Origins-1.16.5-0.7.3.9-forge.jar                  |Origins                       |origins                       |0.7.3.9             |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.157.jar                         |Mantle                        |mantle                        |1.6.157             |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.16.5-FORGE-2.0.5.jar                  |Croptopia                     |croptopia                     |2.0.5               |DONE      |Manifest: NOSIGNATURE
		thermal_cultivation-1.16.5-1.5.0.4.jar            |Thermal Cultivation           |thermal_cultivation           |1.5.0.4             |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		MorePlayerModels-1.16.5.20220731.jar              |More Player Models            |moreplayermodels              |1.16.5.20220731     |DONE      |Manifest: NOSIGNATURE
		camera-1.16.5-1.0.14.jar                          |Camera Mod                    |camera                        |1.16.5-1.0.14       |DONE      |Manifest: NOSIGNATURE
		[1.16.5]+SecurityCraft+v1.9.6.1.jar               |SecurityCraft                 |securitycraft                 |v1.9.6.1            |DONE      |Manifest: NOSIGNATURE
		thermal_expansion-1.16.5-1.5.2.16.jar             |Thermal Expansion             |thermal_expansion             |1.5.2.16            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		entityculling-forge-mc1.16.5-1.5.2.jar            |EntityCulling                 |entityculling                 |1.5.2               |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.16.5-1.7.13.jar                      |Elevator Mod                  |elevatorid                    |1.16.5-1.7.13       |DONE      |Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2.1        |DONE      |Manifest: NOSIGNATURE
		thermal_locomotion-1.16.5-1.5.0.4.jar             |Thermal Locomotion            |thermal_locomotion            |1.5.0.4             |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		cfm-7.0.0pre22-1.16.3.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre22         |DONE      |Manifest: NOSIGNATURE
		architectury-1.32.67.jar                          |Architectury                  |architectury                  |1.32.67             |DONE      |Manifest: NOSIGNATURE
		origins_power_expansion-1.5.0-forge.jar           |Origins Power Expansion       |origins_power_expansion       |1.5.0               |DONE      |Manifest: NOSIGNATURE
		ferritecore-2.1.1-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		cloth-config-4.16.91-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.16.91             |DONE      |Manifest: NOSIGNATURE
		ColdSweat-2.1.11.3.jar                            |Cold Sweat                    |cold_sweat                    |2.1.11.3            |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.16.5-2.1.23.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.23       |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.16.5-2.11.7.jar                     |FallingTree                   |fallingtree                   |2.11.7              |DONE      |Manifest: NOSIGNATURE
		DeExtinction-1.16.3-1.1.0.jar                     |De-Extinction Mod             |deextinction                  |1.1.0               |DONE      |Manifest: NOSIGNATURE
		chiselsandbits-1.0.63.jar                         |Chisels & bits                |chiselsandbits                |1.0.63              |DONE      |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
		PlayerRevive_v2.0.0-pre04_mc1.16.5.jar            |PlayerRevive                  |playerrevive                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.106.jar                 |GeckoLib                      |geckolib3                     |3.0.106             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 8285fc83-12fb-4ec4-b230-25c8be6652ba
	Patchouli open book context: n/a
	Launched Version: 1.16.5-forge-36.2.35
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 531.41, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

**Comment by BobMowzie** [comment]
Remove more player models or turn off my custom player animations.

**Comment by sorvetedaoray** [comment]
how do I turn off the custom player animations?

**Comment by BobMowzie** [comment]
They can be turned off in the mowzies mobs client config file.

**Comment by sorvetedaoray** [comment]
do you know how I can access the mowzies config file on a server? or wich folder is it

**Comment by BobMowzie** [comment]
The server config folder is in the folder called "config". But the client config file, which has the animation settings, does not exist on servers. It changes clientside only properties and so it must be set per user in their installation folders.

For a modpack, you'd have to configure the client config before distributing the pack so that anyone who downloads the pack has your changes.
