### ISSUE TITLE
Cannot join world - ClastCastException - Roughly Enough Resources compat issue

### ISSUE THREAD

**Issue by solonovamax** [BobMowzie/MowziesMobs#752]
There is a `ClassCastException` happening when attempting to join the world, resulting in the player being unable to join, as the server does not start properly.

mod version: 1.6.3
mc version: 1.19.2
forge version: 43.3.13
log: https://mclo.gs/voeCYN9

I believe this is caused due to roughly enough resources being present.

here is the exception:
```
[14:40:36] [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world
java.lang.ClassCastException: class com.bobmowzie.mowziesmobs.server.loot.LootConditionFrostmawHasCrystal cannot be cast to class net.minecraft.world.level.storage.loot.predicates.LootItemKilledByPlayerCondition (com.bobmowzie.mowziesmobs.server.loot.LootConditionFrostmawHasCrystal is in module mowziesmobs@1.6.3 of loader 'TRANSFORMER' @41b66d1; net.minecraft.world.level.storage.loot.predicates.LootItemKilledByPlayerCondition is in module minecraft@1.19.2 of loader 'TRANSFORMER' @41b66d1)
	at net.minecraft.world.level.storage.loot.predicates.LootItemKilledByPlayerCondition$Serializer.m_6170_(LootItemKilledByPlayerCondition.java:38) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.serialize(GsonAdapterFactory.java:125) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%23116!/:?] {}
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%23116!/:?] {}
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95) ~[gson-2.8.9.jar%23116!/:?] {}
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%23116!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%23116!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%23116!/:?] {re:mixin}
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%23116!/:?] {}
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.serialize(LootPool.java:206) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.serialize(LootPool.java:187) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%23116!/:?] {}
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%23116!/:?] {}
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) ~[gson-2.8.9.jar%23116!/:?] {}
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.9.jar%23116!/:?] {}
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%23116!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%23116!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%23116!/:?] {re:mixin}
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%23116!/:?] {}
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.serialize(LootTable.java:279) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.serialize(LootTable.java:253) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%23116!/:?] {}
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%23116!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%23116!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%23116!/:?] {re:mixin}
	at uk.me.desert_island.rer.RoughlyEnoughResources.sendLootToPlayers(RoughlyEnoughResources.java:53) ~[rer-2.6.1.jar%23594!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.players.PlayerList.handler$eel000$onPlayerConnect(PlayerList.java:3952) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,re:classloading,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,pl:mixin:A}
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:247) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,re:classloading,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,pl:mixin:A}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:156) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pluto.mixins.json:network.pipeline.encryption.ServerLoginPacketListenerImplMixin,pl:mixin:APP:connectivity.mixins.json:ServerLoginNetHandlerMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pluto.mixins.json:network.pipeline.encryption.ServerLoginPacketListenerImplMixin,pl:mixin:APP:connectivity.mixins.json:ServerLoginNetHandlerMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pluto.mixins.json:network.pipeline.encryption.ServerLoginPacketListenerImplMixin,pl:mixin:APP:connectivity.mixins.json:ServerLoginNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:1570) [?:?] {re:mixin}
```

**Comment by BobMowzie** [comment]
Fixed! Thanks for reporting
